
name: CI (Test, Lint, Deploy)

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.17 # You can specify the Node.js version you need.

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint
      continue-on-error: true # Continue even if there are linting errors

    - name: Run tests
      run: npm test

  build:
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Login to docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 

    - name: Build docker image
      run: docker build -t jjairojr/void .

    - name: Publish image to docker hub
      run: docker push jjairojr/void

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull jjairojr/void:latest

      - name: Delete old container
        run: docker rm -f void-app
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name void-app jjairojr/void
