
name: CI (Test, Lint, Deploy)

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.17 # You can specify the Node.js version you need.

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint
      continue-on-error: true # Continue even if there are linting errors

    - name: Run tests
      run: npm test

    - name: Checkout source
      uses: actions/checkout@v3

    - name: Login to docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 

    - name: Build docker image
      run: docker build -t void/backend .

    - name: Publish image to docker hub
      run: docker push void/backend:latest

  deploy:
    needs: build
    runs-on: [void-aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull docker push void/backend:latest
      - name: Delete old container
        run: docker rm -f void-app
      - name: Run docker container
        run: docker run -d -p 5000:5000 --name void-app void/backend
